<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Компания Юстиком предоставляет бухгалтерские, аудиторские, кадровые и юридические услуги");
$APPLICATION->SetPageProperty("title", "Подробная информация о компании Юстиком");
$APPLICATION->SetTitle("О компании");
?>

<?
$APPLICATION->IncludeFile(
	SITE_TEMPLATE_PATH . '/include/about/hero-section.php',
	array(
		"EYEBROW_PATH" => "/include/about/eyebrow.php",
		"TITLE_PATH" => "/include/about/title.php",
		"TEXT_PATH" => "/include/about/text.php",
		"BUTTONS_PATH" => "/include/about/buttons.php",
		"IMG_PATH" => "/include/about/img.php",
	),
	array('MODE' => 'html', 'NAME' => 'Внутренний баннер', 'SHOW_BORDER' => false)
);
?>

<?
$APPLICATION->IncludeFile(
	SITE_TEMPLATE_PATH . '/include/about/company-experience/section.php',
	array(
		"EYEBROW_PATH" => "/include/about/company-experience/eyebrow.php",
		"TITLE_PATH" => "/include/about/company-experience/title.php",
		"TEXT_PATH" => "/include/about/company-experience/text.php",
		"IMG_PATH" => "/include/about/company-experience/img.php",
	),
	array('MODE' => 'html', 'NAME' => 'Компания с опытом и репутацией', 'SHOW_BORDER' => false)
);
?>

<? $APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"direction-list",
	[
		"ADD_SECTIONS_CHAIN" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "N",
		"DISPLAY_PREVIEW_TEXT" => "N",
		"FIELD_CODE" => ["NAME"],
		"FILTER_NAME" => "",
		"IBLOCK_ID" => "30",
		"IBLOCK_TYPE" => "usticom_site_content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "N",
		"NEWS_COUNT" => "20",
		"PROPERTY_CODE" => [],
		"SET_BROWSER_TITLE" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_TITLE" => "N",
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "ID",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "ASC",
		"SECTION_TITLE" => "Основные направления:",
		"SECTION_TEXT" => "ЮСТИКОМ — это аудит (обязательный, инициативный и экспресс-аудит), бухгалтерские услуги в диапазоне от консультаций до ведения текущей деятельности, юридическое сопровождение и даже кадровый учет.",
	],
	false,
	["HIDE_ICONS" => "Y"]
); ?>

<? $APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"features",
	[
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "N",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "N",
		"DISPLAY_PREVIEW_TEXT" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => [
			0 => "",
			1 => "",
		],
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "9",
		"IBLOCK_TYPE" => "usticom_site_content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "N",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => [
			0 => "",
			1 => "",
		],
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"COMPONENT_TEMPLATE" => "features",
	],
	false
); ?>

<? $APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"cases",
	[
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "N",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "N",
		"DISPLAY_PREVIEW_TEXT" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => ["NAME", "PREVIEW_PICTURE", "DETAIL_PICTURE", ""],
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "28",
		"IBLOCK_TYPE" => "usticom_site_content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "N",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => ["TAG", ""],
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"COMPONENT_TEMPLATE" => "cases",
		"EYEBROW_TEXT" => "результаты",
		"USE_PAGINATION" => "N",
		"USE_SWIPER_NAVIGATION" => "Y",
		"USE_SWIPER_PAGINATION" => "Y",
		"CARD_TYPE" => "image",
		"SECTION_CLASS" => "section--bg-alternative"
	],
	false
); ?>

<?
$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"news-slider",
	[
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_DATE" => "N",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => ["NAME", "PREVIEW_TEXT", "PREVIEW_PICTURE", "DETAIL_PICTURE", "DATE_ACTIVE_FROM", "DATE_CREATE"],
		"FILTER_NAME" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_TYPE" => "usticom_site_content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "N",
		"NEWS_COUNT" => "6",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PROPERTY_CODE" => ["TAG_LIST"],
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"USE_SWIPER_NAVIGATION" => "Y",
		"USE_SWIPER_PAGINATION" => "N",
		"SHOW_TAG_LIST" => "Y",
		"SHOW_ALL_BUTTON" => "N",
		"SHOW_ALL_BUTTON_TEXT" => "Показать все",
		"IBLOCK_ID" => "7",
		"ACTIVE_DATE_FORMAT" => "j F Y",
		"EYEBROW_TEXT" => "мероприятия",
		"SHOW_ACTIVE_FROM" => "Y",
		"SHOW_ALL_BUTTON_URL" => "/events/",
		"SECTION_CLASS" => "section--bg-initial"
	],
	false,
	["HIDE_ICONS" => "Y"]
);

?>

<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>
